### PR TITLE
Improve security of handling `dashwallet://` uris

### PR DESCRIPTION
**Pull request by tomasz-ludek**
1. Added prompt in Dash Wallet when another app requests the master public key or an address using `dashwallet://...` uri.
2. Used wallet.freshReceiveAddress() instead of wallet.currentReceiveAddress() for address requests.
#77

### CODE REVIEW

**Comment by HashEngineering** [comment]
Can you place the new strings that were added into `wallet/res/values/strings.xml` into `wallet/res/values/strings-extra.xml`?

The reason we do this is to simplify merging from Bitcoin Wallet and it helps insure we don't delete strings by mistake.

**Comment by tomasz-ludek** [comment]
Sure thing!
Done.

**Comment by HashEngineering** [comment]
Review process has begun.

**Comment by HashEngineering** [comment]
Review Complete.  Thank you for this addition.

**Pull request merged**
