### PR TITLE
Targeting Android 28

### PR DESCRIPTION
**Pull request by sambarboza**
# Description
- Target Android 28 API

# Changes
- Created `Transactions` and `Synchronization` notification channels, required when targeting API 26 or later.
- Promoting `BlockchainServiceImpl` to foreground service when synchronizing the blockchain, an ongoing notification will be shown when the app is being synchronized.
- Updated Gradle, Build Tools and Support Library versions.
- Created `BlockchainStateUtlis` class with method to obtain synchronization message across the app.

### CODE REVIEW

**Comment by HashEngineering** [comment]
**On Windows 10 and Android Studio 3.1.4, I got this message:**

> Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.

After changing the gradle wrapper to 4.5, then I was able to build and run on a device.

On Ubunto 16.04 and Android Studio 3.1.4, I get the same error, but it will build with gradle 4.5.

after syncing gradle 4.5, this comes up:

```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'releaseCompile' is obsolete and has been replaced with 'releaseImplementation' and 'releaseApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html


Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

**Comment by HashEngineering** [comment]
When using gradle 4.5, the app can be built and when the blockchain is reset, the above notification in the image is visible when looking at notifications.

**Comment by sambarboza** [comment]
@HashEngineering, fixed gradle warnings.

**Comment by HashEngineering** [comment]
Ok, thanks, I will review this.

**Comment by HashEngineering** [comment]
If I leave it as Gradle - 4.10 - then I still get this error:
```
Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
Open File
```

If I set it to 4.5, then there are no errors or warnings.

**Comment by HashEngineering** [comment]
On android 4.4.4, the notification flashes when resetting the blockchain.

I would be fine with not fixing this.

**Comment by HashEngineering** [comment]
I approve.

Further testing shows that on an emulator, Android 4.4.4 did not have a flickering notification after the blockchain reset.  Additionally, the build worked on Ubuntu 16 with Android Studio 3.1.4.

The text for the notification channels is OK.

**Pull request merged**
