### PR TITLE
Updated ScanActivity to the latest version from bitcoin-wallet

### PR DESCRIPTION
**Pull request by tomasz-ludek**

### CODE REVIEW

**Comment by HashEngineering** [comment]
This will be merged after #243 into the `redesign` branch.

**Comment by HashEngineering** [comment]
After building this and scanning QR codes from the app running on the emulator, the app says on the Payments / Pay screen (with items Pay by Scanning QR code and Pay to copied address) and does not go to the Pay screen.  Pay to copied address still works.  

Unfortunately there are no obvious messages in the logs.

**Comment by tomasz-ludek** [comment]
> After building this and scanning QR codes from the app running on the emulator, the app says on the Payments / Pay screen (with items Pay by Scanning QR code and Pay to copied address) and does not go to the Pay screen. Pay to copied address still works.
> 
> Unfortunately there are no obvious messages in the logs.

Fixed

**Comment by HashEngineering** [comment]
This was merged into the wrong branch and then manually merged here:  https://github.com/HashEngineering/dash-wallet/commit/f1e561b38750378caf638c18c321b7664ff46f55

**Pull request merged**
