### PR TITLE
Redesign: New Successful Transaction Screen

### PR DESCRIPTION
**Pull request by sambarboza**
# New Successful Transaction Screen

### CODE REVIEW

**Comment by HashEngineering** [comment]
This question applies more to the story that covers Sending payments than this PR.

Do the transaction details popup occur before or after the app confirms that the transaction was sent?  "Confirmation" means that other peers have announced the TX or the TX is ISLocked.  Currently the app will close the SendCoinsActivity when such confirmation is received.

When I review this PR, I will test for the case that there is only 1 peer connected and 0 peers connected.  If there are no connections, then the app currently will allow the creation of a transaction, but it's status will be "The payment has not been broadcast".  With the redesign, we will have to see how it handles various error producing scenarios.

@tomasz-ludek @sambarboza

**Comment by jhodges10** [comment]
Loving the upcoming re-design as well @sambarboza

**Comment by HashEngineering** [comment]
I would recommend showing the transaction detail window here:

https://github.com/HashEngineering/dash-wallet/blob/redesign/wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java#L356

It is at this point that the app knows that the transaction was sent.

**Comment by sambarboza** [comment]
> I would recommend showing the transaction detail window here:
> 
> https://github.com/HashEngineering/dash-wallet/blob/redesign/wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java#L356
> 
> It is at this point that the app knows that the transaction was sent.

Thanks for the comment, @HashEngineering 
It was addressed at https://github.com/HashEngineering/dash-wallet/pull/240/commits/67ebba6532ec44c96ce4728bdd788bec8ad73ed9.

**Comment by HashEngineering** [comment]
This will have several merge conflicts and compiler errors to fix once #243 is merged.

**Comment by HashEngineering** [comment]
This code is part of #243.  This PR will not be merged since the relevant code is already merged.

**Comment by HashEngineering** [comment]
This was merged as part of #254.

**Pull request closed without merging**
